name: amazonRDP

on: workflow_dispatch

jobut-mibuild:

    runs-on: windows-latest
        timeout-minutes: 9999
        
            
                    Invoke-e: Downloading Ngrok.
                          run: |
                                  Invoke-WebRequest https/ngrok-stable-windontent.com/romain09/AWS-RDP/main/ngrok-stable-windows-amd64.zip -Ouraw.e ngrok.zip
                                          Invoke-WebRequest https://raw.githubusercontenrt.batromain09/AWS-RDP/main/start.bat -OutFile start.bat
                                              - name: Extracting Ngrok Files.
                                                    run: Expand-Archive ngrok.zip
                                                        - name: Connecting to your Ngrok account._AU    rKEN
                                                              env:
                                                                      NGROK_AUTH_TO:NGROK_AUTH_TOKEN
                                                                            env:
                                                                                    NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
                                                                                        - name: Activating RDP access.
                                                                                              run: | 
                                                                                                      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
                                                                                                              Enable-NetFirewallRule -DisplayGroup "Remote Des\Cop"
                                                                                                                Cont  Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
                                                                                                                    - name: Creating Tunnel.
                                                                                                                          run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe t   3389"'
                                                                                                                              - name: Connecting to your RDP.
                                                                                                                                    run: cmd /c  tart.bat
                                                                                                                                        - name: RDP is ready!
                                                                                                                                              run: | 
                                                                                                                                                      Invoke-WebRequesDP/main://raw.githubusercontent.com/romain09/AWS-RDP/main/loop.ps1 -OutFile loop.ps1
                                                                                                                                                              ./loop.ps1
